export const PACKAGENAME_INIT = 'PACKAGENAME_INIT';
export const PACKAGENAME_INIT_SUCCESS = 'PACKAGENAME_INIT_SUCCESS';
export const PACKAGENAME_INIT_ERROR = 'PACKAGENAME_INIT_ERROR';

export const MENULIST_INIT = 'MENULIST_INIT';
export const MENULIST_INIT_SUCCESS = 'MENULIST_INIT_SUCCESS';
export const MENULIST_INIT_ERROR = 'MENULIST_INIT_ERROR';

export const FILTERLIST_INIT = 'FILTERLIST_INIT';
export const FILTERLIST_INIT_SUCCESS = 'FILTERLIST_INIT_SUCCESS';
export const FILTERLIST_INIT_ERROR = 'FILTERLIST_INIT_ERROR';