export const TOTAL_INCIDENTS = 'TOTAL_INCIDENTS';
export const TOTAL_INCIDENTS_SUCCESS = 'TOTAL_INCIDENTS_SUCCESS';
export const TOTAL_INCIDENTS_ERROR = 'TOTAL_INCIDENTS_ERROR';

export const INCIDENT_VOLUMES = 'INCIDENT_VOLUMES';
export const INCIDENT_VOLUMES_SUCCESS = 'INCIDENT_VOLUMES_SUCCESS';
export const INCIDENT_VOLUMES_ERROR = 'INCIDENT_VOLUMES_ERROR';

export const ACTIVECASE_CHANNEL = 'ACTIVECASE_CHANNEL';
export const ACTIVECASE_CHANNEL_SUCCESS = 'ACTIVECASE_CHANNEL_SUCCESS';
export const ACTIVECASE_CHANNEL_ERROR = 'ACTIVECASE_CHANNEL_ERROR';